### ISSUE TITLE
C compiler errors with `--gc:orc`, when using new style middleware (`app.use`).

### ISSUE THREAD

**Issue by UNIcodeX** [planety/prologue#104]
```nim
import prologue
import prologue/middlewares/staticfile

let settings = newSettings(
  address="0.0.0.0",
  debug=false,
  port=Port(8000),
)

var app = newApp(settings=settings)

app.use(staticFileMiddleware(["/static"]))

proc index(ctx: Context) {.async.} =
  resp """
  <html>
    <body>
      <img src="static/test.jpg" />
    </body>
  </html>
  """

app.addRoute("/", index)

app.run()
```

`nim c -r -d:release --gc:orc main`

```
CC: main.nim
C:\Users\jaredfields\nimcache\main_r\@mmain.nim.c: In function 'use__qN6uFxsHO3zMpVqglPplrgapplication':
C:\Users\jaredfields\nimcache\main_r\@mmain.nim.c:1237:2: error: conversion to non-scalar type requested
  colontmpD_ = (tyVarargs__D9cLSaSQnFjyNDLMFqy9a9a9aQ)0;
  ^~~~~~~~~~
C:\Users\jaredfields\nimcache\main_r\@mmain.nim.c:1238:13: error: incompatible types when assigning to type 'tyVarargs__D9cLSaSQnFjyNDLMFqy9a9a9aQ {aka struct <anonymous>}' from type 'int'
  colontmpD_ = 0;
             ^
C:\Users\jaredfields\nimcache\main_r\@mmain.nim.c:1239:73: error: incompatible type for argument 3 of 'eqcopy___MLN6PVJn0S9b4fK0JYJv0pg'
  eqcopy___MLN6PVJn0S9b4fK0JYJv0pg(colontmpD_.Field0, colontmpD_.Field1, middlewares, middlewaresLen_0);
                                                                         ^~~~~~~~~~~
compilation terminated due to -fmax-errors=3.
Error: execution of an external compiler program 'gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN -O3 -fno-strict-aliasing -fno-ident   -IC:\Users\jaredfields\.choosenim\toolchains\nim-#devel\lib -IC:\Users\jaredfields\Desktop\sandbox\PrologueWebApp -o C:\Users\jaredfields\nimcache\main_r\@mmain.nim.c.o C:\Users\jaredfields\nimcache\main_r\@mmain.nim.c'
failed with exit code: 1
```

NOTE: Works fine with `refc` and `markAndSweep`.

**Comment by ringabout** [comment]
Known issue, not the issue of Prologue.

**Comment by ringabout** [comment]
https://github.com/nim-lang/Nim/issues/15563

**Comment by UNIcodeX** [comment]
My bad. I looked through open and closed issues and didn't see a reference to this. Sorry to clutter up your issues log.

**Comment by ringabout** [comment]
Never mind :)

**Comment by UNIcodeX** [comment]
One thing that is interesting, though. `orc` works with Prologue 3.6 and devel Nim. I'm using that combination in production.

EDIT: Probably because the new static middleware did not exist for that version.

**Comment by ringabout** [comment]
If you don't use `use`, I think it would be fine too.
Old-style middlewares still work in `orc`.

```nim
var app = newApp(settings=settings, middlewares = @[staticFileMiddleware(["/static"])])
```

**Comment by UNIcodeX** [comment]
Indeed; that works!

**Comment by ringabout** [comment]
it seems to be fixed at devel.
